version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command:
      uwsgi --ini uwsgi_docker.ini
