name: Build Docker image

on: [push]
env:
  REPO_URL: docker.pkg.github.com/prokaktus/programming.monster/repository
  GIT_SHA: ${GITHUB_SHA}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Display env
        run: echo $GITHUB_SHA
        shell: bash
      - name: build image
        uses: docker/build-push-action@v1
        with:
          repository: prokaktus/programming.monster/repository
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: 'docker/base/Dockerfile'
          tags: 'latest,${{ env.GIT_SHA }}'
          always_pull: true

#    steps:
#      - uses: actions/checkout@v1
#      - name: Display env
#        run: echo $GITHUB_SHA
#        shell: bash
#      - name: SHA version
#        run: echo ::set-env name=GIT_SHA::$(echo ${GITHUB_SHA:10})
#      - name:
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: prokaktus/programming.monster/repository
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          dockerfile: 'docker/base/Dockerfile'
#          tags: 'latest,${{ env.GIT_SHA }}'
#          cache: true

  tests:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1
      - name: SHA version
        run: echo ::set-env name=GIT_SHA::$(echo ${GITHUB_SHA:10})
      - name: login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: docker run $REPO_URL:$GIT_SHA pytest

#  lint:
#
#    runs-on: ubuntu-latest
#    need: build
#
#    steps:
#      - uses: actions/checkout@v1
#      - name:

