name: Build Docker image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Display env
        run: echo $GITHUB_SHA
        shell: bash
      - name: SHA version
        run: echo ::set-env name=GIT_SHA::$(echo ${GITHUB_SHA:10})
      - name:
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: prokaktus/programming.monster/repository
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: 'docker/base/Dockerfile'
          tags: 'latest,${{ env.GIT_SHA }}'
          cached: true

  tests:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1
      - name: SHA version
        run: echo ::set-env name=GIT_SHA::$(echo ${GITHUB_SHA:10})
      - name: Run tests
        run: docker run -it docker.pkg.github.com/prokaktus/programming.monster/repository:latest pytest
#      - name:
#        uses: ${{ github.actor }}
#        with:
#          entrypoint: pytest
#        env:
#          test: 'test'
