name: Python lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Hello message
        run: |
          echo 'Hello'
      - name:
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: prokaktus/promonster/image
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: '../../../docker/base/Dockerfile'
          workdir: '../../../'
#      - name: Test docker action
#        uses: ./.github/actions/build-container
#        with:
#          who-to-greet: 'Jonny'
