name: Python lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Hello message
        run: |
          echo 'Hello'
      - name: Test docker action
        uses: ./.github/actions/build-container@test-actions
        with:
          who-to-greet: 'Jonny'
