name: Python lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Display env
        run: echo $GITHUB_SHA
        shell: bash
      - name: SHA version
        run: echo ::set-env name=GIT_SHA::$(echo ${GITHUB_SHA:10})
      - name:
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: prokaktus/programming.monster/repository
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: 'docker/base/Dockerfile'
          cache: true
          tags: 'latest,${{ env.GIT_SHA }}'
      - name:
        uses: docker://prokaktus/programming.monster/repository:{{ env.GIT_SHA }}
        with:
          entrypoint: pytest
